### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by lve0200** [AlexandreHiroyuki/MovingAveragePlus#36] opened 2022-11-18 19:49 UTC
I'm using MA w/ Arduino 1.8.16. It appears to me that memory for the MA is not allocated in static RAM, but in heap or stack. At least changing the numbers in "MovingAveragePlus <uint16_t> press_L(20);" has no effect on RAM allocation. Compiler always states "678 Bytes (33%)" dyn memory. That clashs w/ Stack size and the program becomes non executable w/out any error msg. at compilation.

**Comment by AlexandreHiroyuki** [comment] 2022-11-19 04:14
Hi! Thanks for the contribution, I'll work on it as soon as possible.

So, could you help me by providing more information about the problem you're having?
I will ask some questions to try to keep the communication objective.

First,
> It appears to me that memory for the MA is not allocated in static RAM, but in heap or stack.

Why do you expect the MA to be allocated in static memory?

-----------

I'm not sure if I understood what you meant by:
> At least changing the numbers in "MovingAveragePlus <uint16_t> press_L(20);" has no effect on RAM allocation.

Please correct me, but I understood that either you're pushing new data to the MA and the size of the memory allocated isn't changing, or you're changing the size of the MA array but the allocated memory stays the same.

-----------

> That clashs w/ Stack size and the program becomes non executable w/out any error msg. at compilation.

So, what process you used to reach that conclusion? I'm asking this so maybe I could try to reproduce the bug on my environment.

-----------

Also, if you could share some pieces of your code that are suffering from this bug, maybe it could help me understand more about what is happening because I tried running the example code in this repository on my Arduino Nano using this line `MovingAveragePlus <uint16_t> press_L(20);` like it is in your comment, but it worked just fine.

**Comment by AlexandreHiroyuki** [comment] 2022-11-29 21:04
Excuse me, @lve0200. Did you solve your problem? Please, give me some feedback so I can work on the issue or just close it as solved.

**Comment by AlexandreHiroyuki** [comment] 2023-01-12 15:17
I'm closing this issue because I didn't find any problem alone and the OP doesn't answer anymore.

**Closed by AlexandreHiroyuki** 2023-01-12 15:17 UTC
Labels: bug, needs more information, ghosted
